name: 'AI Security Scanner'
description: 'AI-powered security scanning using AWS Bedrock'
author: 'Security Audit Framework'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  aws-region:
    description: 'AWS region for scanning'
    required: false
    default: 'us-east-1'
  
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  
  scan-type:
    description: 'Type of scan (full, incremental, pr)'
    required: false
    default: 'pr'
  
  base-branch:
    description: 'Base branch for PR scans'
    required: false
    default: 'main'
  
  fail-on-critical:
    description: 'Fail the build if critical vulnerabilities found'
    required: false
    default: 'true'
  
  fail-on-high:
    description: 'Fail the build if high vulnerabilities found'
    required: false
    default: 'false'
  
  business-context:
    description: 'Business context for risk scoring (critical, high, normal)'
    required: false
    default: 'normal'
  
  comment-on-pr:
    description: 'Comment scan results on PR'
    required: false
    default: 'true'
  
  upload-sarif:
    description: 'Upload results to GitHub Security tab'
    required: false
    default: 'true'

outputs:
  scan-id:
    description: 'Unique scan ID'
  total-findings:
    description: 'Total number of findings'
  critical-findings:
    description: 'Number of critical findings'
  high-findings:
    description: 'Number of high findings'
  business-risk-score:
    description: 'Business risk score (0-100)'
  report-url:
    description: 'URL to detailed report'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    AWS_REGION: ${{ inputs.aws-region }}
    AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
    AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}